package com.aaron.epsilon_backend.modelos.entidades;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Valoraciones generated by hbm2java
 */
@Entity
@Table(name = "valoraciones")
public class Valoraciones implements java.io.Serializable {

	private int id;
	private Usuarios usuarioValorado;
	private Usuarios usuarioValorador;
	private Integer estrellas;

	public Valoraciones() {
	}

	public Valoraciones(int id, Usuarios usuarioValorado, Usuarios usuarioValorador) {
		this.id = id;
		this.usuarioValorado = usuarioValorado;
		this.usuarioValorador = usuarioValorador;
	}

	public Valoraciones(int id, Usuarios usuarioValorado, Usuarios usuarioValorador,
			Integer estrellas) {
		this.id = id;
		this.usuarioValorado = usuarioValorado;
		this.usuarioValorador = usuarioValorador;
		this.estrellas = estrellas;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario_valorado", nullable = false)
	public Usuarios getUsuarioValorado() {
		return this.usuarioValorado;
	}

	public void setUsuarioValorado(Usuarios usuario) {
		this.usuarioValorado = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario_valorador", nullable = false)
	public Usuarios getUsuarioValorador() {
		return this.usuarioValorador;
	}

	public void setUsuarioValorador(Usuarios usuario) {
		this.usuarioValorado = usuario;
	}

	@Column(name = "estrellas")
	public Integer getEstrelas() {
		return this.estrellas;
	}

	public void setEstrelas(Integer estrellas) {
		this.estrellas = estrellas;
	}

}
